from django.urls import path
from . import views
from . import announcement_views

urlpatterns = [
    path('api/events/', views.EventListView.as_view(), name='event-list'),
    path('api/events/create/', views.CreateEventView.as_view(), name='event-create'),
    path('api/events/<int:event_id>/update/', views.UpdateEventView.as_view(), name='event-update'),
    path('api/events/<int:event_id>/delete/', views.DeleteEventView.as_view(), name='event-delete'),
    path('api/events/types/', views.EventTypeListView.as_view(), name='event-types'),
    path('api/events/<int:event_id>/interest/', views.EventInterestView.as_view(), name='event-interest'),
    path('api/events/<int:event_id>/register/', views.EventRegistrationView.as_view(), name='event-register'),
    path('api/events/<int:event_id>/unregister/', views.EventUnregistrationView.as_view(), name='event-unregister'),
    path('api/events/<int:event_id>/participants/', views.EventParticipantsView.as_view(), name='event-participants'),
    path('api/events/export/', views.ExportEventsView.as_view(), name='event-export'),
    path('api/forum/topics/preview/', views.ForumTopicListView.as_view(), name='forum-topics-preview'),
    path('api/forum/categories/', views.ForumCategoryListView.as_view(), name='forum-categories'),
    path('api/forum/topics/<int:topic_id>/', views.ForumTopicDetailView.as_view(), name='forum-topic-detail'),
    path('api/auth/login/', views.LoginView.as_view(), name='login'),
    path('api/auth/signup/', views.SignupView.as_view(), name='signup'),
    path('api/auth/logout/', views.LogoutView.as_view(), name='logout'),
    path('api/auth/password-reset/', views.request_password_reset, name='password-reset'),
    path('api/auth/password-reset/confirm/', views.reset_password, name='password-reset-confirm'),
    path('api/auth/change-password/', views.ChangePasswordView.as_view(), name='change-password'),
    path('api/dashboard/stats/', views.DashboardStatsView.as_view(), name='dashboard-stats'),
    path('api/moderation/pending/', views.PendingModerationView.as_view(), name='pending-moderation'),
    path('api/dashboard/activity-overview/', views.ActivityOverviewView.as_view(), name='activity-overview'),
    path('api/notifications/', views.NotificationListView.as_view(), name='notification-list'),
    path('api/notifications/mark-read/', views.MarkNotificationsReadView.as_view(), name='mark-notifications-read'),
    path('api/users/profile/', views.UserProfileView.as_view(), name='user-profile'),
    path('api/users/profile/update/', views.UserProfileUpdateView.as_view(), name='user-profile-update'),
    path('api/users/profile/update-picture/', views.UserProfilePictureUpdateView.as_view(), name='user-profile-picture-update'),
    path('api/users/two-factor/', views.TwoFactorAuthView.as_view(), name='two-factor-auth'),
    path('api/users/', views.UserListView.as_view(), name='user-list'),
    path('api/users/create/', views.CreateUserView.as_view(), name='create-user'),
    path('api/users/<int:user_id>/update/', views.UpdateUserView.as_view(), name='update-user'),
    path('api/users/<int:user_id>/delete/', views.DeleteUserView.as_view(), name='delete-user'),
    path('api/users/export/', views.ExportUsersView.as_view(), name='export-users'),
    path('api/announcements/', announcement_views.AnnouncementListView.as_view(), name='announcement-list'),
    path('api/announcements/create/', announcement_views.AnnouncementCreateView.as_view(), name='announcement-create'),
    path('api/announcements/<int:pk>/', announcement_views.AnnouncementDetailView.as_view(), name='announcement-detail'),
    path('api/announcements/<int:pk>/pin/', announcement_views.AnnouncementPinView.as_view(), name='announcement-pin'),
    path('api/announcements/bulk-delete/', announcement_views.AnnouncementBulkDeleteView.as_view(), name='announcement-bulk-delete'),
    path('api/announcements/<int:pk>/comments/', announcement_views.AnnouncementCommentsView.as_view(), name='announcement-comments'),
    path('api/announcements/<int:pk>/like/', announcement_views.AnnouncementLikeView.as_view(), name='announcement-like'),
]