# Generated by Django 5.2 on 2025-06-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blickers_app', '0003_recoverycode_twofactorauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauth',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
