# Generated by Django 5.2 on 2025-06-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blickers_app', '0004_alter_twofactorauth_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Full', 'Full'), ('Past', 'Past'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20),
        ),
    ]
