# Generated by Django 5.2 on 2025-06-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blickers_app', '0006_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manually_set_status',
            field=models.BooleanField(default=False),
        ),
    ]
