# Generated by Django 5.2 on 2025-06-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blickers_app', '0007_event_manually_set_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='announcement_type',
            field=models.CharField(blank=True, choices=[('alert', 'Alerte'), ('info', 'Information'), ('event', 'Événement')], max_length=10, null=True),
        ),
    ]
