# Generated by Django 5.2 on 2025-06-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blickers_app', '0010_forumcategory_color_forumcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forumtopiclike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='forumtopiclike',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='forumtopiclike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forumcategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='forumcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='forumreply',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='status',
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ForumReplyLike',
        ),
        migrations.DeleteModel(
            name='ForumTopicLike',
        ),
    ]
